version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
      - LAMBDA_EXECUTOR=docker
      - DEFAULT_REGION=eu-west-1
      - LAMBDA_NETWORK=bridge
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
